# Generated by Django 5.0.1 on 2024-01-21 01:56

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("latitude", models.CharField(max_length=256)),
                ("longitude", models.CharField(max_length=256)),
                (
                    "expiration_date",
                    models.DateField(default=datetime.date(2024, 1, 23)),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
