# Generated by Django 5.0.1 on 2024-01-21 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2024, 1, 22)),
        ),
    ]
